# ESPHome Secrets File
# Speichere sensible Daten hier

# WiFi Credentials
ssid: "ZTE_0613B3"
wifi_password: "2H6AA4656D"

# MQTT Credentials (optional - nur wenn Authentication aktiviert ist)
mqtt_username: ""
mqtt_password: ""

# OTA Password
ota_password: "cura123"

# API Encryption Key (generiere mit: openssl rand -base64 32)
api_encryption_key: "GENERIERE_EINEN_NEUEN_KEY"
